---

- name: config dir
  file:
    mode: 0700
    state: directory
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    path: "{{ hub_conf|dirname }}"

- name: config file
  template:
    mode: 0600
    dest: "{{ hub_conf }}"
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    src: templates/config.py.j2
  notify: restart hub
