---

- include_tasks: users.yml
- include_tasks: packages.yml
- include_tasks: postgresql.yml

- include_tasks: slides.yml
- include_tasks: nbgrader.yml
- include_tasks: extensions.yml

- include_tasks: config.yml
- include_tasks: service.yml
