---

- name: packages sys
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - npm
      - whois
      - unzip
      - nodejs
      - python3
      - libpq-dev
      - python3-dev
      - python3-pip

- name: packages pip
  pip:
    name:
      - RISE
      - notebook
      - nbgrader
      - psycopg2
      - jupyterhub
      - jupyterhub-systemdspawner
      - jupyter_contrib_nbextensions
    executable: pip3

- name: packages npm
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - configurable-http-proxy

- name: packages perms
  file:
    recurse: true
    path: /usr/local/lib
    mode: "u: rwX,g+rX,o+rX"
