---

- name: postgresql user
  postgresql_user:
    encrypted: true
    name: "{{ hub_sql }}"
    password: "{{ hub_pass }}"
    role_attr_flags: CREATEDB
  become_user: postgres
  become: true

- name: postgresql base
  postgresql_db:
    name: "{{ hub_sql }}"
    owner: "{{ hub_sql }}"
  become_user: postgres
  become: true
