---

- name: service deploy
  template:
    mode: 0640
    dest: "{{ hub_serv }}"
    src: templates/service.j2
  notify: restart hub

- name: service enable
  service:
    name: hub
    enabled: true
