---

- name: members
  user:
    shell: /bin/bash
    name: "{{ item.user }}"
    groups: "{{ hub_group }}"
    update_password: on_create
    password: "{{ item.pass|password_hash('sha512') }}"
  with_items: "{{ students_users }}"

- name: courses
  template:
    mode: 0640
    owner: "{{ item.user }}"
    group: "{{ hub_group }}"
    src: templates/nbgrader_config.py.j2
    dest: "/home/{{ item.user }}/nbgrader_config.py"
  with_items: "{{ students_users }}"
