# ---

- name: users
  user: name='{{item.user}}' groups='{{hub_group}}' shell='/bin/bash' append=true
  with_items: '{{teachers_users}}'

- name: courses
  template: dest='/home/{{item.user}}/nbgrader_config.py' src='templates/nbgrader_config.py.j2' owner='{{item.user}}' group='{{hub_group}}' mode='0640'
  with_items: '{{teachers_users}}'

- name: exchanges
  file: path='{{hub_srv}}/{{item}}' state='directory' owner='{{hub_user}}' group='{{hub_group}}' mode='0777'
  with_items: '{{teachers_courses}}'
