# ---

- name: users
  user:
    append: true
    shell: /bin/bash
    name: "{{ item.user }}"
    groups: "{{ hub_group }}"
  with_items: "{{ teachers_users }}"

- name: courses
  template:
    mode: 0640
    owner: "{{ item.user }}"
    group: "{{ hub_group }}"
    src: templates/nbgrader_config.py.j2
    dest: "/home/{{ item.user }}/nbgrader_config.py"
  with_items: "{{ teachers_users }}"

- name: exchanges
  file:
    mode: 0777
    state: directory
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    path: "{{ hub_srv }}/{{ item }}"
  with_items: "{{ teachers_courses }}"
