---

- name: script
  template: dest='/usr/local/bin/backup' src='templates/backup.j2' owner='root' group='root' mode='700'

- name: schedule
  cron: name='backup' user='root' hour='3' minute='0' job='/usr/local/bin/backup &>> /var/log/backup.log' cron_file='backup'
