---

- name: script
  template:
    mode: 700
    owner: root
    group: root
    dest: /usr/local/bin/backup
    src: templates/backup.j2

- name: schedule
  cron:
    hour: 3
    minute: 0
    user: root
    name: backup
    cron_file: backup
    job: "/usr/local/bin/backup &>> /var/log/backup.log"
