---

- name: root
  user:
    name: root
    shell: /sbin/nologin

- name: packages
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - vim
    - ansible

- name: permissions
  file:
    recurse: true
    owner: "{{ me_user }}"
    group: "{{ me_user }}"
    mode: "u: rwX,g-rwx,o-rwx"
    path: "/home/{{ me_user }}"
