---

- name: private
  openssl_privatekey:
    mode: 0640
    path: "{{ cert_private }}"

- name: request
  openssl_csr:
    mode: 0640
    path: "{{ cert_request }}"
    common_name: "{{ me_site }}"
    privatekey_path: "{{ cert_private }}"

- name: certificate
  openssl_certificate:
    mode: 0640
    provider: selfsigned
    path: "{{ cert_public }}"
    csr_path: "{{ cert_request }}"
    privatekey_path: "{{ cert_private }}"
